src/Entity/Port.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PortRepository")
 */
class Port
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $pin;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Ingredient", inversedBy="port", cascade={"persist", "remove"})
     */
    private $Ingredient;

    public function getId()
    {
        return $this->id;
    }

    public function getPin(): ?int
    {
        return $this->pin;
    }

    public function setPin(int $pin): self
    {
        $this->pin = $pin;

        return $this;
    }

    public function getIngredient(): ?Ingredient
    {
        return $this->Ingredient;
    }

    public function setIngredient(?Ingredient $Ingredient): self
    {
        $this->Ingredient = $Ingredient;

        return $this;
    }
}

templates/assignIngredients.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="ui segment center">
        <button class="ui button green" id="new">
            New
            <i class="right icon plus"></i>
        </button>
    </div>
    <div class="ui segment center">
        <div class="ui items divided">
            {% for port in ports %}
                <div class="item" data-id="{{ port.id }}">
                    <div class="content">
                        <a class="header">Port {{ port.id }}</a>
                        <div class="meta">
                            <div class="ui label">
                                {{ port.ingredient.name }}
                            </div>
                        </div>
                        <div class="description">
                            <p></p>
                        </div>
                        <div class="extra">
                            <div class="ui primary button">
                                Edit
                                <i class="right chevron icon"></i>
                            </div>
                            <div class="ui red button">
                                Remove
                                <i class="right trash icon"></i>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="ui small modal">
        <div class="header">New Port</div>
        <div class="content">
            <div class="ui form">
                <div class="ui field">
                    <div class="ui input">
                        <input type="text" id="port" placeholder="port" class="ui input">
                    </div>
                </div>
                <div class="field">
                    <select class="dropdown ingredient">
                        {% for ingredient in ingredients %}
                            <option value="{{ ingredient.id }}">{{ ingredient.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="actions">
            <div class="ui approve green button">Approve</div>
            <div class="ui cancel red button">Cancel</div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
 {{ parent() }}
 <script>
     $(document).ready(() => {
         $('.item .extra .ui.primary.button').on('click', (event) => {

         });

         function sendPort() {
             let ingredient = $('.modal select').val();
             let pin = $('.modal #port').val();

             $.ajax({
                 method: "POST",
                 url: "/port/create",
                 data: {ingredient: ingredient, pin: pin}
             }).done(() => {
                 location.reload();
             })
         }

         $('#new').on('click', () => {
             $('.ui.small.modal')
                 .modal({
                     onApprove: function () {
                         sendPort()
                     }
                 })
                 .modal('show')
         });

         $('.item .ui.red.button').on('click', (event) => {
             const id = $(event.target).parents('.item').data('id');
             $.ajax({
                 method: "POST",
                 url: '/port/remove',
                 data: {id: id}
             }).done(() => {
                 location.reload();
             })
         });


         $('.dropdown').dropdown();
     })
 </script>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('/jquery/jquery-ui.min.css') }}">
            <link rel="stylesheet" href="{{ asset('/semantic/semantic.min.css') }}">
        {% endblock %}
    </head>
    <body>
        <div class="ui left demo vertical inverted sidebar labeled icon menu visible">
            <a class="item" href="{{ path('index') }}">
                <i class="home icon"></i>
                Home
            </a>
            <a class="item" href="{{ path('pump_ports') }}">
                <i class="object group outline icon"></i>
                Pump Ports
            </a>
            <a class="item" href="{{ path('ingredients') }}">
                <i class="tint layout icon"></i>
                Ingredients
            </a>
            <a class="item" href="{{ path('cocktails') }}">
                <i class="glass martini icon"></i>
                Cocktails
            </a>
        </div>
        <div class="ui grid centered">
            <div class="twelve wide stretched column">
                {% block body %}{% endblock %}
            </div>
        </div>
        {% block javascripts %}
            <script src="{{ asset('/jquery/jquery-3.3.1.min.js') }}"></script>
            <script src="{{ asset('/jquery/jquery-ui.min.js') }}"></script>
            <script src="{{ asset('/semantic/semantic.min.js') }}"></script>
        {% endblock %}
    </body>
</html>

templates/cocktails.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="ui segment center">
        <button class="ui button green" id="new">
            New
            <i class="right icon plus"></i>
        </button>
    </div>
    <div class="ui segment center">
        <div class="ui items divided">
            {% for cocktail in cocktails %}
                <div class="item">
                    <div class="content">
                        <a class="header">{{ cocktail.name }}</a>
                        <div class="meta">
                            {% for ingredient in cocktail.ingredients %}
                                <div class="ui label">
                                    {{ ingredient.name }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="description">
                            <p></p>
                        </div>
                        <div class="extra">
                            <div class="ui primary button">
                                Edit
                                <i class="right chevron icon"></i>
                            </div>
                            <div class="ui red button">
                                Remove
                                <i class="right trash icon"></i>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="ui small modal">
        <div class="header">New Cocktail</div>
        <div class="content">
            <div class="ui form">
                <div class="ui field">
                    <div class="ui input">
                        <input type="text" id="name" placeholder="name" class="ui input">
                    </div>
                </div>
                <div class="field holder">
                    <div class="two fields">
                        <div class="field">
                            <select class="dropdown ingredient">
                                {% for ingredient in ingredients %}
                                    <option value="{{ ingredient.id }}">{{ ingredient.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="field">
                            <input type="number" class="amount" placeholder="number">
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui button positive" id="new_ingredient">
                new Ingredient
            </div>
        </div>
        <div class="actions">
            <div class="ui approve green button">Approve</div>
            <div class="ui cancel red button">Cancel</div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
 {{ parent() }}
 <script>
     $(document).ready(() => {
         $('.item .extra .ui.primary.button').on('click', (event) => {

         });

         function sendCocktail() {
             let ingredientsFields = $('.modal select');
             const name = $('.modal #name').val();
             const ingredients = [];
             ingredientsFields.each((index, value) => {
                 console.log(value);
                 const amount = $(value).parents('.holder').find('.amount').val();
                 ingredients.push({ingredient: $(value).val(), amount: amount});
             });

             $.ajax({
                 method: "POST",
                 url: "/cocktail/create",
                 data: {ingredients: ingredients, name: name}
             }).done(() => {
                 //location.reload();
             })
         }

         $('#new').on('click', () => {
             $('.ui.small.modal')
                 .modal({
                     onApprove: function () {
                         sendCocktail()
                     }
                 })
                 .modal('show')
         });


         $('.dropdown').dropdown();

         $('#new_ingredient').on('click', (event) => {
             $(event.target).parents('.content').find('.form').append('' +
                 '<div class="field">\n' +
                 '                    <div class="two fields">\n' +
                 '                        <div class="field">\n' +
                 '                            <select>\n' +
                 '                                {% for ingredient in ingredients %}\n' +
                 '                                    <option value="{{ ingredient.id }}">{{ ingredient.name }}</option>\n' +
                 '                                {% endfor %}\n' +
                 '                            </select>\n' +
                 '                        </div>\n' +
                 '                        <div class="field">\n' +
                 '                            <input type="number" placeholder="number">\n' +
                 '                        </div>\n' +
                 '                    </div>\n' +
                 '                </div>');
             $('.dropdown').dropdown();
         })
     })
 </script>
{% endblock %}

templates/index.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="ui segment center">
        <button class="ui button green" id="new">
            New
            <i class="right icon plus"></i>
        </button>
    </div>
    <div class="ui segment center">
        <div class="ui items divided">
            {% for cocktail in cocktails %}
                <div class="item" data-cocktail="{{ cocktail.id }}">
                    <div class="content">
                        <a class="header">{{ cocktail.name }}</a>
                        <div class="meta">
                            {% for ingredient in cocktail.ingredients %}
                                <div class="ui label">
                                    {{ ingredient.name }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="description">
                            <p></p>
                        </div>
                        <div class="extra">
                            <div class="ui primary button make">
                                Make
                                <i class="right chevron icon"></i>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="ui container">
        <div class="ui segment center">
            <div class="ui form">
                <div class="grouped fields">
                    <div class="field">
                        <div class="ui toggle checkbox">
                            <input type="checkbox" name="pin21" data-pin="21" class="pump-control">
                            <label>Pump 1</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui toggle checkbox">
                            <input type="checkbox" name="pin20" data-pin="20" class="pump-control">
                            <label>Pump 2</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui toggle checkbox">
                            <input type="checkbox" name="pin26" data-pin="26" class="pump-control">
                            <label>Pump 3</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui toggle checkbox">
                            <input type="checkbox" name="pin19" data-pin="19" class="pump-control">
                            <label>Pump 4</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
 {{ parent() }}
 <script>
     $(document).ready(() => {
         $('.pump-control').on('click', (event) => {
             let on = $(event.target).prop('checked');
             let pin = $(event.target).data('pin');
             $.ajax({
                 url: '/pump/send',
                 method: "POST",
                 data: {on: on, pin: pin}
             });
         });

         $('.primary.button.make').on('click', (event) => {
             const cocktail = $(event.target).parents('.item').data('cocktail');
             $.ajax({
                 url: '/cocktail/make',
                 method: "POST",
                 data: {id: cocktail}
             });
         })
     })
 </script>
{% endblock %}

templates/ingredients.html.twig
{% extends "base.html.twig" %}
{% block body %}
    <div class="ui segment center">
        <button class="ui button green" id="new">
            New
            <i class="right icon plus"></i>
        </button>
    </div>
    <div class="ui segment center">
        <div class="ui items divided">
            {% for ingredient in ingredients %}
                <div class="item" data-id="{{ ingredient.id }}">
                    <div class="content">
                        <a class="header">{{ ingredient.name }}</a>
                        <div class="extra">
                            <div class="ui primary button">
                                Edit
                                <i class="right chevron icon"></i>
                            </div>
                            <div class="ui red button">
                                Remove
                                <i class="right trash icon"></i>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="ui small modal">
        <div class="header">New Ingredient</div>
        <div class="content">
            <div class="ui form">
                <div class="ui input">
                    <input type="text" id="name" placeholder="name" class="ui input">
                </div>
                <div class="ui input">
                    <input type="text" id="time" placeholder="time" class="ui input">
                </div>
            </div>
        </div>
        <div class="actions">
            <div class="ui approve green button">Approve</div>
            <div class="ui cancel red button">Cancel</div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
 {{ parent() }}
 <script>
     $(document).ready(() => {
         $('#new').on('click', () => {
             $('.ui.small.modal')
                 .modal({
                     onApprove : function(event) {
                         const name = $('.ui.small.modal').find('#name').val();
                         const time = $('.ui.small.modal').find('#time').val();
                         sendIngredient(name, time)
                     }
                 })
                 .modal("show")
         });
         $('.ui.small.modal').on('onapprove', (event) => {
             console.log(event)
         });

         $('.item .ui.red.button').on('click', (event) => {
             const id = $(event.target).parents('.item').data('id');
             $.ajax({
                 method: "POST",
                 url: '/ingredient/remove',
                 data: {id: id}
             }).done(() => {
                 window.location.reload();
             })
         });

         function sendIngredient(name, time) {
             $.ajax({
                 method: "POST",
                 url: "/ingredient/create",
                 data: {name: name, time: time}
             }).done(() => {
                 window.location.reload();
             })
         }
     })
 </script>
{% endblock %}